# Generated by Django 4.2.1 on 2023-10-28 06:32

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentic_rating',
            field=models.CharField(default='100', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='Vendor Description', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='vendor.jpg', upload_to=userauths.models.user_directory_path),
        ),
    ]
